### ISSUE TITLE
Create User pages

### ISSUE THREAD

**Issue by LeanKhan** [hapy-lang/hapy-land#10]
- Create login page
- Create register page
- Create user page: here users can see their codes etc

**Comment by alummav** [comment]
> * Create login page
> * Create register page
> * Create user page: here users can see their codes etc

I want to add a separate CSS stylesheet to the login page but its not working. i saved the CSS in the layouts folder

**Comment by LeanKhan** [comment]
@alummav  Is it working now?

**Comment by alummav** [comment]
> @alummav Is it working now?

at all bro, i need to change the code of the login page tho. i want to make sure it uses both the base code and it own code

**Comment by LeanKhan** [comment]
First go to the second hapy-land, `C:\done\sdp\hapy-land\hapy-land>`. Then try the command again, make sure there is not space before the `app`. `uvicorn main:app --reload`

**Comment by alummav** [comment]
i've done it bro, thank you

*The information contained in this e-mail and any attachments are for the
use of the named recipient only.*

*This e-mail including any attachments is confidential and may be legally
privileged. If you have received it in error please advise the sender
immediately by return e-mail and then delete it from your system without
making or retaining any copies and without disclosing the contents to any
third party. The unauthorized use, distribution, copying or alteration of
this email is strictly forbidden.*


*Regards,*
*Victor Alumma*

**Comment by LeanKhan** [comment]
> > @alummav Is it working now?
> 
> at all bro, i need to change the code of the login page tho. i want to make sure it uses both the base code and it own code

Add a style element to the `head` of the page and put your css there. Inside the "head" block put your styles element.

```html
% block head %}
    {{ super() }}
<style>
// put your CSS styles here...
</style>
{% endblock %}
```

Try to google the issues first

**Comment by alummav** [comment]
@LeanKhan I have committed and pushed, have you seen it

**Comment by LeanKhan** [comment]
Hey, I haven't seen it. What message did it give you?

**Comment by alummav** [comment]
> Hey, I haven't seen it. What message did it give you?

C:\done\sdp\hapy-land\hapy-land>git commit -m "user-pages"
[master b0c4cdd] user-pages
 8 files changed, 170 insertions(+), 7 deletions(-)
 create mode 100644 hapy-land/frontend/templates/layouts/base-2.html
 create mode 100644 hapy-land/frontend/templates/layouts/loginform.css
 create mode 100644 hapy-land/frontend/templates/login.html
 delete mode 100644 hapy-land/frontend/templates/partials/navbar.html
 create mode 100644 hapy-land/frontend/templates/register.html

C:\done\sdp\hapy-land\hapy-land>git pull
Already up to date.

C:\done\sdp\hapy-land\hapy-land>git status
On branch master
Your branch is ahead of 'origin/master' by 1 commit.
  (use "git push" to publish your local commits)

nothing to commit, working tree clean

C:\done\sdp\hapy-land\hapy-land>git push
git: 'credential-manager' is not a git command. See 'git --help'.

The most similar command is
        credential-manager-core
Enumerating objects: 23, done.
Counting objects: 100% (23/23), done.
Delta compression using up to 4 threads
Compressing objects: 100% (13/13), done.
Writing objects: 100% (14/14), 2.64 KiB | 103.00 KiB/s, done.
Total 14 (delta 6), reused 0 (delta 0), pack-reused 0
remote: Resolving deltas: 100% (6/6), completed with 6 local objects.
To https://github.com/hapy-lang/hapy-land
   468e99e..b0c4cdd  master -> master

C:\done\sdp\hapy-land\hapy-land>git status
On branch master
Your branch is up to date with 'origin/master'.

nothing to commit, working tree clean

C:\done\sdp\hapy-land\hapy-land>

**Comment by alummav** [comment]
@LeanKhan server no wan load oh

Microsoft Windows [Version 10.0.19042.1288]
(c) Microsoft Corporation. All rights reserved.

C:\Users\Emmanuel Segun-Lean>cd ../../done/sdp/hapy-land

C:\done\sdp\hapy-land>venv\Scripts\activate

(venv) C:\done\sdp\hapy-land>uvicorn main: app --reload
Usage: uvicorn [OPTIONS] APP
Try 'uvicorn --help' for help.

Error: Got unexpected extra argument (app)

(venv) C:\done\sdp\hapy-land>uvicorn main: app --reload
Usage: uvicorn [OPTIONS] APP
Try 'uvicorn --help' for help.

Error: Got unexpected extra argument (app)

(venv) C:\done\sdp\hapy-land>

**Comment by LeanKhan** [comment]
Yo, you were on the wrong branch. Why were you in master??

**Comment by LeanKhan** [comment]
You have already oushed to master so no need to create a Pull Request. Please abeg, don't push from master again. We make pull requests from **other** branches so that we can see what we are doing.

Next time just checkout to that your branch make your commits and push from there. thanks.
nice work :+1:

**Comment by alummav** [comment]
ah i thought you said we should checkout to master when we want to commit?

**Comment by alummav** [comment]
no wahala

**Comment by alummav** [comment]
i'm back on user branch, I didn't make any changes in the master sha

**Comment by LeanKhan** [comment]
> i'm back on user branch, I didn't make any changes in the master sha

Lolo you did o, you committed into Master. That's what I'm saying. Check the github, you;ll see the latest changes are from You. 😬

**Comment by alummav** [comment]
omo no vex, na pressure. i want to commit this user branch and push what's there. how should I do this?

**Comment by alummav** [comment]
no wait, the user branch does not even have the login and register p, I want to merge the user branch to the master branch so that it would update

**Comment by alummav** [comment]
LEAANNNN

**Comment by alummav** [comment]
don't worry ive switched to master without commiting, please how do I go about updating the user branch and making the necessary changes from there

**Comment by alummav** [comment]
should i merge?

**Comment by LeanKhan** [comment]
> don't worry ive switched to master without commiting, please how do I go about updating the user branch and making the necessary changes from there

Hey, you have already made the necessary changes bro. Or is there something else you added?

**Comment by LeanKhan** [comment]
> omo no vex, na pressure. i want to commit this user branch and push what's there. how should I do this?

oh sorry, no pressure bro 🌈

**Comment by LeanKhan** [comment]
Compare the output of `git log --one-line -n 5` in the two branches.

**Comment by alummav** [comment]
> Compare the output of `git log --one-line -n 5` in the two branches. Sha that git command I sent one time to check the commit history.

C:\done\sdp\hapy-land\hapy-land>git status
On branch user
nothing to commit, working tree clean

C:\done\sdp\hapy-land\hapy-land>git log --one-line -n 5
fatal: unrecognized argument: --one-line

C:\done\sdp\hapy-land\hapy-land>git log --oneline -n 5
912ee14 (HEAD -> user) Merge branch 'master' into user
797c2a2 user-pages
b0c4cdd (origin/master, origin/HEAD, master) user-pages
468e99e diamond
c608255 CDN-icons

C:\done\sdp\hapy-land\hapy-land>git checkout master
Switched to branch 'master'
Your branch is up to date with 'origin/master'.

C:\done\sdp\hapy-land\hapy-land>git log --oneline -n 5
b0c4cdd (HEAD -> master, origin/master, origin/HEAD) user-pages
468e99e diamond
c608255 CDN-icons
eb0e9c2 background-color
109287d Api develop (#8)

**Comment by LeanKhan** [comment]
Looks like you're good

**Comment by alummav** [comment]
> Looks like you're good

bro where are you?
