### ISSUE TITLE
After a pull

### ISSUE THREAD

**Issue by LeanKhan** [hapy-lang/hapy-land#21]
After you've updated your local code with changes from remote, there are some things you need to do:

- Activate the virtual env first before you install pip packages. `venv\Scripts\activate`
-  Run `pip install -r requirements.txt` in the directory the requirements file is located. This installs any Python packages that may have been downloaded. 
- Run `npm install` in the directory that has the package.json file. This installs any Nodejs packages that may have been downloaded by others.
- Make sure your `.env` file has all the variables you need. Ask a teammate for a copy of yours. We don't commit `.env` files because they can contain sensitive information like passwords.

If you've done all of this, you should be good to go. Start the dang server! 🎸

**Comment by alummav** [comment]
> After you've updated your local code with changes from remote, there are some things you need to do:
> 
> * Run `pip install -r requirements.txt` in the directory the requirements file is located. This installs any Python packages that may have been downloaded.
> * Run `npm install` in the directory that has the package.json file. This installs any Nodejs packages that may have been downloaded by others.
> * Make sure your `.env` file has all the variables you need. Ask a teammate for a copy of yours. We don't commit `.env` files because they can contain sensitive information like passwords.
> 
> If you've done all of this, you should be good to go. Start the dang server! 🎸

C:\>cd ../../done/sdp/hapy-land/venv

C:\done\sdp\hapy-land\venv>pip install -r requirements.txt
ERROR: Could not open requirements file: [Errno 2] No such file or directory: 'requirements.txt'
WARNING: You are using pip version 21.2.4; however, version 21.3.1 is available.
You should consider upgrading via the 'C:\Users\Emmanuel Segun-Lean\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\python.exe -m pip install --upgrade pip' command.

C:\done\sdp\hapy-land\venv>

**Comment by alummav** [comment]
@leankhan check this

**Comment by LeanKhan** [comment]
@alummav first, activate the virtual env like this:
Go to the first hapy-land folder, then run `venv\Scripts\activate`

Then run the pip install command.

**Comment by LeanKhan** [comment]
> @LeanKhan check this

Sorry man, I forgot to add that you have to activate the virtual environment before you install the pip packages. I've updated the message.

**Comment by alummav** [comment]
> > @LeanKhan check this
> 
> Sorry man, I forgot to add that you have to activate the virtual environment before you install the pip packages. I've updated the message.


(venv) C:\done\sdp\hapy-land\hapy-land>cd ..

(venv) C:\done\sdp\hapy-land>venv\Scripts\ativate
'venv\Scripts\ativate' is not recognized as an internal or external command,
operable program or batch file.

(venv) C:\done\sdp\hapy-land>venv\Scripts\activate

(venv) C:\done\sdp\hapy-land>pip install -r requirements.txt
Looking in indexes: https://pypi.org/simple, https://test.pypi.org/simple/
Collecting alembic==1.7.5
  Downloading alembic-1.7.5-py3-none-any.whl (209 kB)
     |████████████████████████████████| 209 kB 145 kB/s
Requirement already satisfied: anyio==3.3.4 in c:\done\sdp\hapy-land\venv\lib\site-packages (from -r requirements.txt (line 4)) (3.3.4)
Requirement already satisfied: asgiref==3.4.1 in c:\done\sdp\hapy-land\venv\lib\site-packages (from -r requirements.txt (line 5)) (3.4.1)
Requirement already satisfied: certifi==2021.10.8 in c:\done\sdp\hapy-land\venv\lib\site-packages (from -r requirements.txt (line 6)) (2021.10.8)
Requirement already satisfied: charset-normalizer==2.0.7 in c:\done\sdp\hapy-land\venv\lib\site-packages (from -r requirements.txt (line 7)) (2.0.7)
Requirement already satisfied: click==8.0.3 in c:\done\sdp\hapy-land\venv\lib\site-packages (from -r requirements.txt (line 8)) (8.0.3)
Requirement already satisfied: click-default-group==1.2.2 in c:\done\sdp\hapy-land\venv\lib\site-packages (from -r requirements.txt (line 9)) (1.2.2)
Requirement already satisfied: colorama==0.4.4 in c:\done\sdp\hapy-land\venv\lib\site-packages (from -r requirements.txt (line 10)) (0.4.4)
Requirement already satisfied: dnspython==2.1.0 in c:\done\sdp\hapy-land\venv\lib\site-packages (from -r requirements.txt (line 11)) (2.1.0)
Requirement already satisfied: email-validator==1.1.3 in c:\done\sdp\hapy-land\venv\lib\site-packages (from -r requirements.txt (line 12)) (1.1.3)
Requirement already satisfied: fastapi==0.70.0 in c:\done\sdp\hapy-land\venv\lib\site-packages (from -r requirements.txt (line 13)) (0.70.0)
Requirement already satisfied: greenlet==1.1.2 in c:\done\sdp\hapy-land\venv\lib\site-packages (from -r requirements.txt (line 14)) (1.1.2)
Requirement already satisfied: h11==0.12.0 in c:\done\sdp\hapy-land\venv\lib\site-packages (from -r requirements.txt (line 15)) (0.12.0)
Collecting Hapy==0.4.0
  Downloading https://test-files.pythonhosted.org/packages/b7/b4/572fd3af1c7e83a51f07dc7c71542b279a074b0b725809689faee77957c9/Hapy-0.4.0-py3-none-any.whl (33 kB)
Requirement already satisfied: httptools==0.2.0 in c:\done\sdp\hapy-land\venv\lib\site-packages (from -r requirements.txt (line 17)) (0.2.0)
Requirement already satisfied: idna==3.3 in c:\done\sdp\hapy-land\venv\lib\site-packages (from -r requirements.txt (line 18)) (3.3)
Requirement already satisfied: itsdangerous==2.0.1 in c:\done\sdp\hapy-land\venv\lib\site-packages (from -r requirements.txt (line 19)) (2.0.1)
Requirement already satisfied: Jinja2==3.0.2 in c:\done\sdp\hapy-land\venv\lib\site-packages (from -r requirements.txt (line 20)) (3.0.2)
Collecting Mako==1.1.5
  Downloading Mako-1.1.5-py2.py3-none-any.whl (75 kB)
     |████████████████████████████████| 75 kB 85 kB/s
Requirement already satisfied: MarkupSafe==2.0.1 in c:\done\sdp\hapy-land\venv\lib\site-packages (from -r requirements.txt (line 22)) (2.0.1)
Requirement already satisfied: orjson==3.6.4 in c:\done\sdp\hapy-land\venv\lib\site-packages (from -r requirements.txt (line 23)) (3.6.4)
Requirement already satisfied: pydantic==1.8.2 in c:\done\sdp\hapy-land\venv\lib\site-packages (from -r requirements.txt (line 24)) (1.8.2)
Requirement already satisfied: python-dotenv==0.19.1 in c:\done\sdp\hapy-land\venv\lib\site-packages (from -r requirements.txt (line 25)) (0.19.1)
Requirement already satisfied: python-multipart==0.0.5 in c:\done\sdp\hapy-land\venv\lib\site-packages (from -r requirements.txt (line 26)) (0.0.5)
Requirement already satisfied: PyYAML==5.4.1 in c:\done\sdp\hapy-land\venv\lib\site-packages (from -r requirements.txt (line 27)) (5.4.1)
Requirement already satisfied: requests==2.26.0 in c:\done\sdp\hapy-land\venv\lib\site-packages (from -r requirements.txt (line 28)) (2.26.0)
Requirement already satisfied: six==1.16.0 in c:\done\sdp\hapy-land\venv\lib\site-packages (from -r requirements.txt (line 29)) (1.16.0)
Requirement already satisfied: sniffio==1.2.0 in c:\done\sdp\hapy-land\venv\lib\site-packages (from -r requirements.txt (line 30)) (1.2.0)
Requirement already satisfied: SQLAlchemy==1.4.26 in c:\done\sdp\hapy-land\venv\lib\site-packages (from -r requirements.txt (line 31)) (1.4.26)
Collecting SQLAlchemy-Utils==0.37.9
  Downloading SQLAlchemy_Utils-0.37.9-py3-none-any.whl (100 kB)
     |████████████████████████████████| 100 kB 146 kB/s
Requirement already satisfied: starlette==0.16.0 in c:\done\sdp\hapy-land\venv\lib\site-packages (from -r requirements.txt (line 33)) (0.16.0)
Requirement already satisfied: typing-extensions==3.10.0.2 in c:\done\sdp\hapy-land\venv\lib\site-packages (from -r requirements.txt (line 34)) (3.10.0.2)
Requirement already satisfied: ujson==4.2.0 in c:\done\sdp\hapy-land\venv\lib\site-packages (from -r requirements.txt (line 35)) (4.2.0)
Requirement already satisfied: urllib3==1.26.7 in c:\done\sdp\hapy-land\venv\lib\site-packages (from -r requirements.txt (line 36)) (1.26.7)
Requirement already satisfied: uvicorn==0.15.0 in c:\done\sdp\hapy-land\venv\lib\site-packages (from -r requirements.txt (line 37)) (0.15.0)
Requirement already satisfied: watchgod==0.7 in c:\done\sdp\hapy-land\venv\lib\site-packages (from -r requirements.txt (line 38)) (0.7)
Requirement already satisfied: websockets==10.0 in c:\done\sdp\hapy-land\venv\lib\site-packages (from -r requirements.txt (line 39)) (10.0)
Installing collected packages: Mako, SQLAlchemy-Utils, Hapy, alembic
  Attempting uninstall: Hapy
    Found existing installation: Hapy 0.2.0
    Uninstalling Hapy-0.2.0:
      Successfully uninstalled Hapy-0.2.0
Successfully installed Hapy-0.4.0 Mako-1.1.5 SQLAlchemy-Utils-0.37.9 alembic-1.7.5
WARNING: You are using pip version 21.2.4; however, version 21.3.1 is available.
You should consider upgrading via the 'C:\done\sdp\hapy-land\venv\Scripts\python.exe -m pip install --upgrade pip' command.

(venv) C:\done\sdp\hapy-land>uvicon main:app --reload
'uvicon' is not recognized as an internal or external command,
operable program or batch file.

(venv) C:\done\sdp\hapy-land>uvicorn main:app --reload
INFO:     Will watch for changes in these directories: ['C:\\done\\sdp\\hapy-land']
INFO:     Uvicorn running on http://127.0.0.1:8000 (Press CTRL+C to quit)
INFO:     Started reloader process [11616] using watchgod
ERROR:    Error loading ASGI app. Could not import module "main".
INFO:     Stopping reloader process [11616]

(venv) C:\done\sdp\hapy-land>cd hapy-land

(venv) C:\done\sdp\hapy-land\hapy-land>uvicorn main:app --reload
INFO:     Will watch for changes in these directories: ['C:\\done\\sdp\\hapy-land\\hapy-land']
INFO:     Uvicorn running on http://127.0.0.1:8000 (Press CTRL+C to quit)
INFO:     Started reloader process [15412] using watchgod
Process SpawnProcess-1:
Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.2288.0_x64__qbz5n2kfra8p0\lib\multiprocessing\process.py", line 315, in _bootstrap
    self.run()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.2288.0_x64__qbz5n2kfra8p0\lib\multiprocessing\process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "C:\done\sdp\hapy-land\venv\lib\site-packages\uvicorn\subprocess.py", line 76, in subprocess_started
    target(sockets=sockets)
  File "C:\done\sdp\hapy-land\venv\lib\site-packages\uvicorn\server.py", line 68, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.2288.0_x64__qbz5n2kfra8p0\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.2288.0_x64__qbz5n2kfra8p0\lib\asyncio\base_events.py", line 642, in run_until_complete
    return future.result()
  File "C:\done\sdp\hapy-land\venv\lib\site-packages\uvicorn\server.py", line 76, in serve
    config.load()
  File "C:\done\sdp\hapy-land\venv\lib\site-packages\uvicorn\config.py", line 448, in load
    self.loaded_app = import_from_string(self.app)
  File "C:\done\sdp\hapy-land\venv\lib\site-packages\uvicorn\importer.py", line 21, in import_from_string
    module = importlib.import_module(module_str)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.2288.0_x64__qbz5n2kfra8p0\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "C:\done\sdp\hapy-land\hapy-land\.\main.py", line 2, in <module>
    from api.main import api
  File "C:\done\sdp\hapy-land\hapy-land\.\api\main.py", line 12, in <module>
    from .database import SessionLocal, engine
  File "C:\done\sdp\hapy-land\hapy-land\.\api\database.py", line 10, in <module>
    ENV = os.getenv("ENV").strip()
AttributeError: 'NoneType' object has no attribute 'strip'

**Comment by LeanKhan** [comment]
In your `.env` file copy and paste this:

```
ENV=DEV
DEV_DB_URL=sqlite:///./sql_app.db
```

**Comment by alummav** [comment]
> In your `.env` file copy and paste this:
> 
> ```
> ENV=DEV
> DEV_DB_URL=sqlite:///./sql_app.db
> ```

done sir, what next?

**Comment by LeanKhan** [comment]
Yeah start the server again bro

**Comment by alummav** [comment]
> Yeah start the server again bro

restarted

**Comment by LeanKhan** [comment]
Great. Nice
