### ISSUE TITLE
merging master

### ISSUE THREAD

**Issue by LeanKhan** [hapy-lang/hapy-land#5]
@alummav yo

**Comment by LeanKhan** [comment]
How far, what was the problem exactly?

**Comment by alummav** [comment]
oh yeah this is what i did just now



C:\done\sdp\hapy-land>git merge --abort

C:\done\sdp\hapy-land>git checkout bootstrap
Switched to branch 'bootstrap'
Your branch is behind 'origin/bootstrap' by 2 commits, and can be fast-forwarded.
  (use "git pull" to update your local branch)

C:\done\sdp\hapy-land>git checkout master
Switched to branch 'master'
Your branch and 'origin/master' have diverged,
and have 1 and 2 different commits each, respectively.
  (use "git pull" to merge the remote branch into yours)

**Comment by LeanKhan** [comment]
Have tried to do `git pull` again?

**Comment by alummav** [comment]
CONFLICT (add/add): Merge conflict in hapy-land/frontend/templates/partials/navbar-2.html
Auto-merging hapy-land/frontend/templates/partials/navbar-2.html
Auto-merging hapy-land/frontend/templates/layouts/base.html
CONFLICT (content): Merge conflict in hapy-land/frontend/templates/layouts/base.html
Auto-merging hapy-land/frontend/templates/example.html
CONFLICT (content): Merge conflict in hapy-land/frontend/templates/example.html
Automatic merge failed; fix conflicts and then commit the result.

**Comment by alummav** [comment]
just now thats what it showed

**Comment by LeanKhan** [comment]
I have already resolved the conflicts from master man. Lemme try it on my system. You can't have a conflict in master unless you made changes in master. Did you?

**Comment by LeanKhan** [comment]
I just pulled from master right now. It merged. So maybe you made changes in master?

**Comment by alummav** [comment]
my sublime was in master when i saw the weird text on some of the files. I just deleted it and forgot to switch branches this morning

**Comment by alummav** [comment]
should i merge?

**Comment by alummav** [comment]
chek the website you'll see what I'm talking about

**Comment by LeanKhan** [comment]
> my sublime was in master when i saw the weird text on some of the files. I just deleted it and forgot to switch branches this morning

what did you delete?

**Comment by alummav** [comment]
> > my sublime was in master when i saw the weird text on some of the files. I just deleted it and forgot to switch branches this morning
> 
> what did you delete?

random numbers that were on the code, nothing serious

**Comment by alummav** [comment]
check the actual website o, youll see the random numbers

**Comment by LeanKhan** [comment]
> random numbers that were on the code, nothing serious

Do you know how they got there? I'm trying to figure out the source of all this. There should be no issue when updating master.

**Comment by LeanKhan** [comment]
> check the actual website o, youll see the random numbers

Do you remember what file?

**Comment by alummav** [comment]
> > check the actual website o, youll see the random numbers
> 
> Do you remember what file?

like it wasn't on a separate file, they were on the different webpage code files

**Comment by alummav** [comment]
think it was when this laptop switched off

**Comment by LeanKhan** [comment]
> like it wasn't on a separate file, they were on the different webpage code files

hmm. What different webpage? I've checked the much of code it looks good to me. Okay let's try to get your `master` branch to the normal state.

1. do `git status` in master and paste what it says

**Comment by alummav** [comment]
C:\done\sdp\hapy-land>git status
On branch master
Your branch and 'origin/master' have diverged,
and have 1 and 2 different commits each, respectively.
  (use "git pull" to merge the remote branch into yours)

You have unmerged paths.
  (fix conflicts and run "git commit")
  (use "git merge --abort" to abort the merge)

Unmerged paths:
  (use "git add <file>..." to mark resolution)
        both modified:   hapy-land/frontend/templates/example.html
        both modified:   hapy-land/frontend/templates/layouts/base.html
        both added:      hapy-land/frontend/templates/partials/navbar-2.html

no changes added to commit (use "git add" and/or "git commit -a")

**Comment by LeanKhan** [comment]
Okay,have you tried `git merge --abort`?

**Comment by alummav** [comment]
> Okay,have you tried `git merge --abort`?Then let's see what `git log --oneline -5` says. This will print the last 5 commits in `master`.

C:\done\sdp\hapy-land>git merge --abort

C:\done\sdp\hapy-land>git status
On branch master
Your branch and 'origin/master' have diverged,
and have 1 and 2 different commits each, respectively.
  (use "git pull" to merge the remote branch into yours)

nothing to commit, working tree clean

C:\done\sdp\hapy-land>

**Comment by LeanKhan** [comment]
Okay cool, then try `git log --oneline -5` to see the last five commits, I'll compare them with mine

**Comment by alummav** [comment]
C:\done\sdp\hapy-land>git log --oneline -5
78dd9f1 (HEAD -> master) Edits to Website
17fcbe4 add layout (#2)
521b78c rename backend -> frontend
a489aaa Merge pull request #1 from hapy-lang/frontend-1
0e557ba (origin/frontend-1, frontend-1) Addition of the Hapy webpages

**Comment by LeanKhan** [comment]
I see. There is a divergence.
This is mine:

2985144 (HEAD -> master, origin/master, origin/HEAD) English and Hausa Buttons (#4)
f511eab Bootstrap (#3)
17fcbe4 add layout (#2)
521b78c rename backend -> frontend
a489aaa Merge pull request #1 from hapy-lang/frontend-1

Okay, let's remove some of those commits. I wonder how they got there.

**Comment by LeanKhan** [comment]
Okay, let's try something a little _risky_.

`git reset --hard 17fcbe4` since that is the last commit that matches the remote

**Comment by alummav** [comment]
okay

**Comment by alummav** [comment]
> Okay, let's try something a little _risky_.
> 
> `git reset --hard 17fcbe4` since that is the last commit that matches the remote.
> 
> Explanation: We are trying to go back to the 'Add layout' commit. [See source](https://stackoverflow.com/a/11708691/10382407)

git reset --hard 17fcbe4
HEAD is now at 17fcbe4 add layout (#2)

**Comment by LeanKhan** [comment]
> > Okay, let's try something a little _risky_.
> > `git reset --hard 17fcbe4` since that is the last commit that matches the remote.
> > Explanation: We are trying to go back to the 'Add layout' commit. [See source](https://stackoverflow.com/a/11708691/10382407)
> 
> git reset --hard [17fcbe4](https://github.com/hapy-lang/hapy-land/commit/17fcbe4b3137e850f35dd3edae411bb8e126789f) HEAD is now at [17fcbe4](https://github.com/hapy-lang/hapy-land/commit/17fcbe4b3137e850f35dd3edae411bb8e126789f) add layout (#2)

Perfect.

Do a `git fetch` (to see what's up in the remote repo), then do `git status` (to see if there are still divergences)

**Comment by alummav** [comment]
C:\done\sdp\hapy-land>git fetch

C:\done\sdp\hapy-land>git status
On branch master
Your branch is behind 'origin/master' by 2 commits, and can be fast-forwarded.
  (use "git pull" to update your local branch)

nothing to commit, working tree clean

C:\done\sdp\hapy-land>

**Comment by alummav** [comment]
> C:\done\sdp\hapy-land>git fetch
> 
> C:\done\sdp\hapy-land>git status On branch master Your branch is behind 'origin/master' by 2 commits, and can be fast-forwarded. (use "git pull" to update your local branch)
> 
> nothing to commit, working tree clean
> 
> C:\done\sdp\hapy-land>

doing the git pull now

**Comment by alummav** [comment]
>git pull
Updating 17fcbe4..2985144
Fast-forward
 hapy-land/frontend/static/style.css                |  0
 hapy-land/frontend/templates/bite.html             |  9 +++-
 hapy-land/frontend/templates/example.html          | 51 ++++++++++++++--------
 hapy-land/frontend/templates/index.html            | 45 ++++++++++++++-----
 hapy-land/frontend/templates/layouts/base.html     | 16 +++----
 .../frontend/templates/partials/navbar-2.html      | 21 +++++++++
 6 files changed, 101 insertions(+), 41 deletions(-)
 create mode 100644 hapy-land/frontend/static/style.css
 create mode 100644 hapy-land/frontend/templates/partials/navbar-2.html

C:\done\sdp\hapy-land>git log --oneline -5
2985144 (HEAD -> master, origin/master, origin/HEAD) English and Hausa Buttons (#4)
f511eab Bootstrap (#3)
17fcbe4 add layout (#2)
521b78c rename backend -> frontend
a489aaa Merge pull request #1 from hapy-lang/frontend-1

**Comment by alummav** [comment]
we're good now, so right now i should create a new branch ba?

**Comment by LeanKhan** [comment]
Done, you're good. Yes create a new branch from an **up-to-date** `master` anytime you are working on something new.

**Comment by alummav** [comment]
yes sir.

**Comment by LeanKhan** [comment]
"Something new" usually refers to:

- A bug you are fixing
- A new feature (like a page) you are adding
- Enhancements (like adding color)

👍

**Comment by alummav** [comment]
> "Something new" usually refers to:
> 
> * A bug you are fixing
> * A new feature (like a page) you are adding
> * Enhancements (like adding color)
> 
> 👍

so right now the master is updated, new branch coming rn naming it icons.
