### ISSUE TITLE
icons

### ISSUE THREAD

**Issue by alummav** [hapy-lang/hapy-land#6]
@LeanKhan i downloaded bootstrap icons. how can i access them. see the com line code

Microsoft Windows [Version 10.0.19042.1237]
(c) Microsoft Corporation. All rights reserved.

C:\Users\Emmanuel Segun-Lean>npm i bootstrap-icons
npm WARN saveError ENOENT: no such file or directory, open 'C:\Users\Emmanuel Segun-Lean\package.json'
npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN enoent ENOENT: no such file or directory, open 'C:\Users\Emmanuel Segun-Lean\package.json'
npm WARN Emmanuel Segun-Lean No description
npm WARN Emmanuel Segun-Lean No repository field.
npm WARN Emmanuel Segun-Lean No README data
npm WARN Emmanuel Segun-Lean No license field.

+ bootstrap-icons@1.6.1
added 1 package from 1 contributor and audited 1 package in 19.575s
found 0 vulnerabilities

**Comment by LeanKhan** [comment]
Hapy-land is not a NodeJS project so it cannot install packages using NPM. However, that is not the only way to add icons.

https://icons.getbootstrap.com/#install

The Icons website also gives the option of downloading the icons or using a CDN. Directions are there. For development let's just use a CDN. So copy that command into the `base.html` <head> section.

**Comment by alummav** [comment]
> Hapy-land is not a NodeJS project so it cannot install packages using NPM. However, that is not the only way to add icons.
> 
> https://icons.getbootstrap.com/#install
> 
> The Icons website also gives the option of downloading the icons or using a CDN. Directions are there. For development let's just use a CDN. So copy that command into the `base.html` section.

done
